//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RickVowens
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Material()
        {
            this.MaterialOfProduct = new HashSet<MaterialOfProduct>();
            this.SuppliesMaterialsInMaterialStockContains = new HashSet<SuppliesMaterialsInMaterialStockContains>();
        }
    
        public int IDMaterial { get; set; }
        public string Name { get; set; }
        public int CountInStock { get; set; }
        public decimal CostWithoutNDS { get; set; }
        public virtual decimal CostWithNDS { get { return CostWithoutNDS * 1.2m; } }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialOfProduct> MaterialOfProduct { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SuppliesMaterialsInMaterialStockContains> SuppliesMaterialsInMaterialStockContains { get; set; }
    }
}
