//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RickVowens
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ShoesKursovoiEntities : DbContext
    {
        public ShoesKursovoiEntities()
            : base("name=ShoesKursovoiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Departaments> Departaments { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<Gender> Gender { get; set; }
        public virtual DbSet<Material> Material { get; set; }
        public virtual DbSet<MaterialOfProduct> MaterialOfProduct { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<Production> Production { get; set; }
        public virtual DbSet<ProductionContain> ProductionContain { get; set; }
        public virtual DbSet<Shops> Shops { get; set; }
        public virtual DbSet<SuppliesMaterialsInMaterialStock> SuppliesMaterialsInMaterialStock { get; set; }
        public virtual DbSet<SuppliesMaterialsInMaterialStockContains> SuppliesMaterialsInMaterialStockContains { get; set; }
        public virtual DbSet<SuppliesProductsInProductStock> SuppliesProductsInProductStock { get; set; }
        public virtual DbSet<SuppliesProductsInProductStockContains> SuppliesProductsInProductStockContains { get; set; }
        public virtual DbSet<SuppliesProductsInShops> SuppliesProductsInShops { get; set; }
        public virtual DbSet<SuppliesProductsInShopsContains> SuppliesProductsInShopsContains { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TypeOfProduct> TypeOfProduct { get; set; }
    }
}
