//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RickVowens
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.MaterialOfProduct = new HashSet<MaterialOfProduct>();
            this.ProductionContain = new HashSet<ProductionContain>();
            this.SuppliesProductsInProductStockContains = new HashSet<SuppliesProductsInProductStockContains>();
            this.SuppliesProductsInShopsContains = new HashSet<SuppliesProductsInShopsContains>();
        }
    
        public int Articul { get; set; }
        public int IDType { get; set; }
        public string Name { get; set; }
        public int CountInStock { get; set; }
        public string Image { get; set; }
        public int IdGender { get; set; }
        public string Age { get; set; }
        public decimal CostWithoutNDS { get; set; }
        public virtual string ImagePath { get { return AppDomain.CurrentDomain.BaseDirectory + "..\\..\\" + Image; } }
        public virtual decimal CostWithNDS { get { return CostWithoutNDS * 1.2m; } }
        public virtual string MemoryCacheKey { get { return Articul + Name; } }

        public virtual Gender Gender { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialOfProduct> MaterialOfProduct { get; set; }
        public virtual TypeOfProduct TypeOfProduct { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductionContain> ProductionContain { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SuppliesProductsInProductStockContains> SuppliesProductsInProductStockContains { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SuppliesProductsInShopsContains> SuppliesProductsInShopsContains { get; set; }
    }
}
