//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RickVowens
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductionContain
    {
        public int Articul { get; set; }
        public int CountOfProduct { get; set; }
        public int ID { get; set; }
        public int IDProduction { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Production Production { get; set; }
    }
}
