//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RickVowens
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuppliesProductsInProductStockContains
    {
        public int ID { get; set; }
        public int IDSupply { get; set; }
        public int ShoeArticul { get; set; }
        public int CountOfShoe { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual SuppliesProductsInProductStock SuppliesProductsInProductStock { get; set; }
    }
}
