//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RickVowens
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuppliesMaterialsInMaterialStockContains
    {
        public int ID { get; set; }
        public int IDSupply { get; set; }
        public int IDMaterial { get; set; }
        public int CountOfMaterial { get; set; }
    
        public virtual Material Material { get; set; }
        public virtual SuppliesMaterialsInMaterialStock SuppliesMaterialsInMaterialStock { get; set; }
    }
}
